site_name: 'Computer Security'
site_author: 'Deian Stefan'

theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  favicon: 'images/favicon.png'

extra:
  social:
    - type: 'github'
      link: 'https://github.com/PLSysSec/cse227-fall18'

markdown_extensions:
  - admonition
  - footnotes
  - toc:
      permalink: true

extra_css:
  - css/extra.css

pages:
  - About: index.md
  - Syllabus: syllabus.md
  - Contact information: contact.md
  - Project ideas: ideas.md
  - Hall of fame: fame.md
